version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r5t
      MYSQL_DATABASE: alpaca_auth
      MYSQL_USER: alpaca-app-user
      MYSQL_PASSWORD: 1q2w3e4r
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - alpaca_network

  redis:
    image: redis:6.2
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - alpaca_network

volumes:
  mysql_data:

networks:
  alpaca_network:
    driver: bridge
