spring:
  application:
    name: alpaca-connector
  datasource:
    url: jdbc:mysql://localhost:3306/alpaca_auth
    username: alpaca-app-user
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

alpaca:
  api:
    key: PKADEEGJNEGXRS20X486
    secret: A0EdkjEg1Igfttry6fnqgV87A096aglOiSW8Vhmx
  base:
    url: https://paper-api.alpaca.markets/v2

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    com.algostrategix.alpacatrdeapi: DEBUG
